name: jobster
services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=jobster'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5435:5432'
    volumes:
      - app-data:/app/uploads

volumes:
  app-data: